version: '3.1'

services:

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - "./docker_volumes/mysql:/var/lib/mysql"
    command: ['--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--max_connections=3000'
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

